name: RuboCop Annotate Action
description: GitHub Action for creating annotations from RuboCop results
author: "Nikolay Norkin <zduderman@gmail.com>"
branding:
  icon: alert-triangle
  color: purple
inputs:
  path:
    required: true
    description: path to RuboCop results JSON file
    default: rubocop.json
runs:
  using: node16
  main: dist/index.js
