name: CI

on: [push, pull_request]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v2
        with:
          path:
          key: yarn-${{ hashFiles('yarn.json') }}
          restore-keys: |
            yarn-
      - run: yarn install
      - run: yarn run build
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v2
        with:
          path:
          key: yarn-${{ hashFiles('yarn.json') }}
          restore-keys: |
            yarn-
      - run: yarn install
      - run: yarn run test
  prettier:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v2
        with:
          path:
          key: yarn-${{ hashFiles('yarn.json') }}
          restore-keys: |
            yarn-
      - run: yarn install
      - run: yarn run format-check
  lint:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v2
        with:
          path:
          key: yarn-${{ hashFiles('yarn.json') }}
          restore-keys: |
            yarn-
      - run: yarn install
      - run: yarn run lint
